---
title: "Parking Study"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

Parking Capacity Data: 


```{r, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}
library(xlsx)
library(readxl)
library(plotly)
library(sf)
library(dplyr)
library(tidygeocoder)
library(leaflet)
library(rgdal)
library(dplyr)
library(rmarkdown)
library(crosstalk)
library(lubridate)
library(htmltools)
library(remotes)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}
devtools::install_github("wsp-sag/tcadr")
install.packages('htmltools')
library(tcadr)

##read_tcad("inst/extdata/TransitR.bin")

##https://github.com/wsp-sag/tcadr


SE_2013 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/SE_2013-rev.bin")


SE_2025 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM SE Data Inputs/2025/SE_2025.bin")

SE_2045 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM SE Data Inputs/2045/SE_2045.bin")



Stud_Off_2045 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM MTP Inputs Scenario Years/2045 MTP wAmendments/Input/Univ/Stud_Off Total 2045.bin")



library(dplyr)

SE_2025_sum <- SE_2025 %>%
  group_by(PASA) %>%
  summarize(n = n(),
            work = sum(Industry + Office + Service_RateLow + Service_RateHigh + Retail),
            vistor = sum(Service_RateLow + Service_RateHigh + Retail))


SE_2045_sum <- SE_2045 %>%
  group_by(PASA) %>%
  summarize(n = n(),
            work = sum(Industry + Office + Service_RateLow + Service_RateHigh + Retail),
            vistor = sum(Service_RateLow + Service_RateHigh + Retail))

SE_2045_sum$University <- NA

SE_2045_sum$University[2] <- sum(Stud_Off_2045$UNC)
SE_2045_sum$University[3] <- sum(Stud_Off_2045$DUKE)
SE_2045_sum$University[4] <- sum(Stud_Off_2045$NCSU)
SE_2045_sum$University[5] <- sum(Stud_Off_2045$NCCU)

SE_2045_sum=SE_2045_sum[-1,]




###Add Park Capcity files
ParkCap_2013 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM MTP Inputs Scenario Years/2013 Base Year/Input/Programs/Parkcap.bin")
ParkCap_2016 <- tcadr::read_tcad("C:/Users/JacobFo/TRMv6.2/Original TRMv6.2_2016/Input/Programs/Parkcap.bin")
ParkCap_2025 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM MTP Inputs Scenario Years/2045 MTP wAmendments/Input/Programs/Parkcap.bin")
ParkCap_2035 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM MTP Inputs Scenario Years/2035 MTP wAmendments/Input/Programs/Parkcap.bin")
ParkCap_2045 <- tcadr::read_tcad("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/TRM MTP Inputs Scenario Years/2045 MTP wAmendments/Input/Programs/Parkcap.bin")

ParkCap_2013$Year <- 2013
ParkCap_2016$Year <- 2016
ParkCap_2025$Year <- 2025
ParkCap_2035$Year <- 2035
ParkCap_2045$Year <- 2045

All_Caps <- rbind(ParkCap_2013, ParkCap_2016, ParkCap_2025, ParkCap_2035, ParkCap_2045)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

labels = c("1 = UNC Campus",
"2 = Duke Campus",
"3 = NCSU Campus",
"4 = NCCU Campus",
"5 = Chapel Hill CBD",
"6 = Durham CBD",
"7 = Raleigh CBD",
"8 = Carrboro CBD",
"9 = Hillsborough CBD",
"10=RDU"


)

levels = c(1,2,3,4,5,6,7,8,9,10)

All_Caps$PASA <- ordered(All_Caps$PASA,
                         levels=levels,
                         labels=labels)

library(lubridate)

lubridate::ymd(All_Caps$Year, truncated=2L)

```




##Existing Parking capacity data from SVN repository: ##



```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(DT)
datatable(All_Caps, filter='top',
          caption="Parking Capacities for PASAs for 2013, 2016, 2025, 2035 and 2045")
```

